app = "bug-less-validator"
primary_region = "gig"

[http_service]
internal_port = 10000
force_https = true

[http_service.concurrency]
type = "requests"
soft_limit = 200
hard_limit = 250

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/healthz"

[env]
CARTESI_LOG_LEVEL = "info"
CARTESI_LOG_TIMESTAMP = "false"
CARTESI_FEATURE_HOST_MODE = "false"
CARTESI_FEATURE_DISABLE_CLAIMER = "false"
CARTESI_HTTP_PORT = "10000"
CARTESI_HTTP_ADDRESS = "0.0.0.0"
CARTESI_FEATURE_DISABLE_MACHINE_HASH_CHECK = "true"
CARTESI_FEATURE_READER_MODE = "false"
CARTESI_SNAPSHOT_DIR = "/usr/share/cartesi/snapshot"
CARTESI_BLOCKCHAIN_ID = "11155111"
CARTESI_BLOCKCHAIN_IS_LEGACY = "false"
CARTESI_BLOCKCHAIN_FINALITY_OFFSET = "1"
CARTESI_CONTRACTS_APPLICATION_ADDRESS = "0x5c7A258c4B833B31D51f105F8dEb5A5233156cf9"
CARTESI_CONTRACTS_APPLICATION_DEPLOYMENT_BLOCK_NUMBER = "5382002"
CARTESI_CONTRACTS_HISTORY_ADDRESS = "0x19558bc901C21f7C81a582999cA786B7018087d3"
CARTESI_CONTRACTS_AUTHORITY_ADDRESS = "0x5D1B6D937Dd1c75Ed1a681e12834cb629caae705"
CARTESI_CONTRACTS_INPUT_BOX_ADDRESS = "0x59b22D57D4f067708AB0c00552767405926dc768"
CARTESI_CONTRACTS_INPUT_BOX_DEPLOYMENT_BLOCK_NUMBER = "3963384"
CARTESI_EPOCH_DURATION = "86400"

# SECRETS
# should be created before deploying the app using `fly secrets set`
# CARTESI_BLOCKCHAIN_HTTP_ENDPOINT=
# CARTESI_BLOCKCHAIN_WS_ENDPOINT=
# CARTESI_AUTH_MNEMONIC=
# CARTESI_POSTGRES_ENDPOINT=
