#!/bin/sh

# bounty and exploit paths
BOUNTY_TAR=$1
BOUNTY_WORKDIR=$2
EXPLOIT_FILE=$3

# user and shell
BWRAPBOX_TERM=linux
BWRAPBOX_USER=bounty
BWRAPBOX_HOME=/bounty
BWRAPBOX_WORKDIR=/bounty
BWRAPBOX_PATH=/usr/bin:/bin

# seccomp
BWRAPBOX_SECCOMP_FILTER=/usr/lib/bwrapbox/seccomp-filter.bpf

# cgroups
BWRAPBOX_CLIMIT_CGROUP_MAX_DESCENDANTS=32
BWRAPBOX_CLIMIT_CGROUP_MAX_DEPTH=32
BWRAPBOX_CLIMIT_CPU_WEIGHT_NICE=5

# memory
BWRAPBOX_CLIMIT_MEMORY_SWAP_MAX=0
BWRAPBOX_CLIMIT_MEMORY_HIGH=$((48*1024*1024))
BWRAPBOX_CLIMIT_MEMORY_MAX=$((64*1024*1024))
BWRAPBOX_RLIMIT_MEMLOCK_MAX=$((64*1024*1024))
BWRAPBOX_RLIMIT_DATA_MAX=$((64*1024*1024))
BWRAPBOX_RLIMIT_STACK_MAX=$((8*1024*1024))

# virtual memory address space
BWRAPBOX_RLIMIT_AS_HIGH=$((48*1024*1024))
BWRAPBOX_RLIMIT_AS_MAX=$((64*1024*1024))

# cpu time (in seconds)
BWRAPBOX_RLIMIT_CPU_MAX=5

# storage
BWRAPBOX_RLIMIT_CORE_MAX=0
BWRAPBOX_TMP_SIZE=$((16*1024*1024))

# pids
BWRAPBOX_CLIMIT_PIDS_MAX=32
BWRAPBOX_RLIMIT_NPROC_MAX=32
BWRAPBOX_RLIMIT_NICE_MAX=5

# files
BWRAPBOX_RLIMIT_NOFILE_MAX=1024
BWRAPBOX_RLIMIT_FSIZE_MAX=$((32*1024*1024))

# priority
BWRAPBOX_RLIMIT_RTPRIO_MAX=0
BWRAPBOX_RLIMIT_RTTIME_MAX=0

# signals
BWRAPBOX_RLIMIT_SIGPENDING_MAX=64

# message queue
BWRAPBOX_RLIMIT_MSGQUEUE_MAX=0

# cgroup cpu time
BWRAPBOX_CLIMIT_TIME_HIGH=$(((BWRAPBOX_RLIMIT_CPU_MAX+1)*1000*1000))
BWRAPBOX_CLIMIT_TIME_MAX=$(((BWRAPBOX_RLIMIT_CPU_MAX+2)*1000*1000))

# cgroup real time
BWRAPBOX_CLIMIT_ELAPSED_HIGH=$(((BWRAPBOX_RLIMIT_CPU_MAX+3)*1000*1000))
BWRAPBOX_CLIMIT_ELAPSED_MAX=$(((BWRAPBOX_RLIMIT_CPU_MAX+4)*1000*1000))

################################################################################

# exit when command fails
set -e

# extract bounty files
rm -rf $BOUNTY_WORKDIR
mkdir -p $BOUNTY_WORKDIR
cd $BOUNTY_WORKDIR
tar xf $BOUNTY_TAR --warning=no-timestamp

# run bounty test in sandboxed environment
bwrapbox \
  --cgroup $BWRAPBOX_USER.bwrapbox \
  --cgroup-overwrite \
  --setuid $(id -u $BWRAPBOX_USER) \
  --setgid $(id -g $BWRAPBOX_USER) \
  --dev /dev \
  --proc /proc \
  --ro-bind /usr /usr \
  --ro-bind /etc /etc \
  --ro-bind /sys /sys \
  --ro-bind $BOUNTY_WORKDIR $BWRAPBOX_WORKDIR \
  --perms 1777 --size $BWRAPBOX_TMP_SIZE --tmpfs /tmp \
  --symlink /usr/lib /lib \
  --symlink /usr/bin /bin \
  --symlink /run /var/run \
  --symlink /tmp /var/tmp \
  --ro-bind $EXPLOIT_FILE /exploit \
  --remount-ro / \
  --unshare-ipc \
  --unshare-pid \
  --unshare-net \
  --unshare-uts \
  --unshare-user \
  --clearenv \
  --setenv TERM $BWRAPBOX_TERM \
  --setenv PATH $BWRAPBOX_PATH \
  --setenv HOME $BWRAPBOX_HOME \
  --setenv USER $BWRAPBOX_USER \
  --setenv LOGNAME $BWRAPBOX_USER \
  --chdir $BWRAPBOX_WORKDIR \
  --die-with-parent \
  --as-pid-1 \
  --new-session \
  -- /bounty/start.sh /exploit

