on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'cli'
      - 'cloud'
      - 'frontend'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      IMAGE_NAME: bug-buster-machine
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3

      - name: Build bounty examples
        run: make bounties

      - name: Extract metadata from Git refs and GitHub events
        id: extract_metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build machine image and push it to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          builder: ${{ steps.setup_buildx.outputs.name }}
          tags: ${{ steps.extract_metadata.outputs.tags }}
          labels: ${{ steps.extract_metadata.lables.labels }}
          cache-from: type=gha,scope=ubuntu
          cache-to: type=gha,mode=max,scope=ubuntu
